# -*- coding: utf-8 -*-
"""boxplot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QetCBbBQuO1QNaUB8ZMeW2xtrTZkm0e1
"""

from sklearn.datasets import fetch_california_housing
import pandas as pd
import matplotlib.pyplot as plt

# Load California Housing dataset
housing = fetch_california_housing(as_frame=True)

# Features + target as a single DataFrame
df = housing.frame

# Quick check
print(df.head())
print(df.shape)

# you can save the boxplot
# save figs/boxplot.png
df.boxplot(figsize=(10, 4))

plt.savefig('figs/boxplot.png')
